//! Demo 关卡的 tile 布局常量数据。

pub const DEMO_GROUND_WIDTH: usize = 96;
pub const DEMO_GROUND_HEIGHT: usize = 16;

const EMPTY: Option<u16> = None;
const GRASS: Option<u16> = Some(0);
const DIRT: Option<u16> = Some(1);
const STONE: Option<u16> = Some(2);

pub const DEMO_GROUND: [[Option<u16>; DEMO_GROUND_WIDTH]; DEMO_GROUND_HEIGHT] = [
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [GRASS; DEMO_GROUND_WIDTH],
    [DIRT; DEMO_GROUND_WIDTH],
    [DIRT; DEMO_GROUND_WIDTH],
    [DIRT; DEMO_GROUND_WIDTH],
    [STONE; DEMO_GROUND_WIDTH],
    [STONE; DEMO_GROUND_WIDTH],
    [STONE; DEMO_GROUND_WIDTH],
];
