pub const DEMO_GROUND_WIDTH: usize = 32;
pub const DEMO_GROUND_HEIGHT: usize = 16;

const EMPTY: Option<u16> = None;
const GRASS: Option<u16> = Some(0);
const DIRT: Option<u16> = Some(1);
const STONE: Option<u16> = Some(2);
const FLOWER: Option<u16> = Some(3);

pub const DEMO_GROUND: [[Option<u16>; DEMO_GROUND_WIDTH]; DEMO_GROUND_HEIGHT] = [
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [EMPTY; DEMO_GROUND_WIDTH],
    [
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, FLOWER,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, FLOWER, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
    ],
    [GRASS; DEMO_GROUND_WIDTH],
    [DIRT; DEMO_GROUND_WIDTH],
    [DIRT; DEMO_GROUND_WIDTH],
    [
        DIRT, DIRT, DIRT, STONE, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, STONE,
        DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, STONE, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT,
        DIRT, DIRT,
    ],
    [STONE; DEMO_GROUND_WIDTH],
    [STONE; DEMO_GROUND_WIDTH],
    [STONE; DEMO_GROUND_WIDTH],
];
